### ISSUE TITLE
A lista de alunos deveria estar em ordem alfabética

### ISSUE THREAD

**Issue by rwnobrega** [emersonmello/gitcurso#7]
A lista de alunos no arquivo `alunos.md` deveria estar em ordem alfabética para facilitar a localização dos nomes.

**Comment by emersonmello** [comment]
olá @rwnobrega , concordo!

@professoramayara , por favor, poderia a fazer a correção e mandar um novo PR?

No PR, tente referenciar o número dessa issue.

obrigado

**Comment by professoramayara** [comment]
@emersonmello assim que possível executo está tarefa. Estou sem acesso ao computador no momento.
